### ISSUE TITLE
Theming issues

### ISSUE THREAD

**Issue by MrGrigri** [Pictogrammers/Browser-Icon-Picker#103]
I'm currently using Edge on a Mac and there are some inconsistencies with theming. It seams that when the plugin is set to light, that is where the issues lie. If the plugin is set to dark, then there aren't any issues.

Not working scenarios

| System | Browser | Plugin |
|--------|--------|--------|
| Light | System Default | Light | Header and icon menu is lost |
| Light | Light | Light | Header and icon menu is lost |
| Dark | Light | Light | Header and icon menu is lost |
| Auto | System Default | Light | Header and icon menu is lost |
| Auto | Light | Light | Header and icon menu is lost |

Working scenarios

| System | Browser | Plugin |
|--------|--------|--------|
| Light | System Default | Dark | 
| Light | Light | Dark | 
| Light | Dark | Light | 
| Light | Dark | Dark | 
| Dark | System Default | Light | 
| Dark | System Default | Dark |
| Dark | Light | Dark |
| Dark | Dark | Light | 
| Dark | Dark | Dark |
| Auto | System Default |
| Auto | Light | Dark | 
| Auto | Dark | Light |
| Auto | Dark | Dark |

<img width="398" alt="image" src="https://user-images.githubusercontent.com/4528551/228337745-ddb88563-ef2c-4f6e-abd0-ef57603b8a89.png">

**Comment by chteuchteu** [comment]
Thank you for this crystal clear issue! I was able to reproduce the issue and fix it, I'll prepare a new release!
