### ISSUE TITLE
Intercept Links to MDI Site

### ISSUE THREAD

**Issue by JamesCoyle** [Pictogrammers/Browser-Icon-Picker#8]
Would be great if it would intercept links to specific icons on the MDI site and show the extension instead. For example, clicking on `https://materialdesignicons.com/icon/backup-restore` would open the extension and show the `backup-restore` icon rather than navigating to the link. Shouldn't be an issue with the new site but waiting a good 10-20 seconds every time the site opens is pretty annoying.

**Comment by chteuchteu** [comment]
Indeed!

> waiting a good 10-20 seconds every time the site opens is pretty annoying

That's the main reason I created this extension actually.

**Comment by Templarian** [comment]
New site fixes this (pretty much instant), same URL schema. Can't wait to get this finished up more to launch.

**Comment by chteuchteu** [comment]
Should we still implement this? IMHO, force-replacing the site with the extension isn't a great idea - especially if performance issues will be addresses in a soon-to-be-released version

**Comment by chteuchteu** [comment]
Last commit still applies - we may detect that current tab's URL looks like `https://materialdesignicons.com/icon/{name}`, and select the right icon when the popup opens. WDYT?

**Comment by chteuchteu** [comment]
As suggested by #98, closing as wontfix
