### ISSUE TITLE
Ability to copy PNG icon from picker

### ISSUE THREAD

**Issue by squidgemonster** [Pictogrammers/Browser-Icon-Picker#92]
Thanks SO much for this super handy picker for MDI. Although I use the 'Copy SVG' action a lot when art working - there are some instances where the software I'm using doesn't accept SVGs - so I have to use the 'View on MDI' option to go to the main site, and copy the PNG from there instead.

Any chance of adding this option into the picker instead? :)

**Comment by chteuchteu** [comment]
That's legitimate, I'll look into it!

**Comment by chteuchteu** [comment]
It's been deployed: may I ask you to test it?

**Comment by squidgemonster** [comment]
Sure - I'll take a look and get back to you. Thanks for putting that feature in 😊

**Comment by chteuchteu** [comment]
@squidgemonster You're right, let me fix that! Releasing 3.11.2.
