### ISSUE TITLE
Update links in the picker to the new website

### ISSUE THREAD

**Issue by mririgoyen** [Pictogrammers/Browser-Icon-Picker#98]
We need to update the extension to start pointing to the new site. Here's all the places that I have found that should be updated (I might have missed some!).

- The Header's link to go to https://pictogrammers.com/library/mdi
- Each icon's "View on MDI" should now link to https://pictogrammers.com/library/mdi/icon/{ICON_NAME}
- "Copy markdown preview"s content should be updated to...
  ```
  [![ICON_NAME](https://pictogrammers.com/library/mdi/icon/{ICON_NAME)](https://pictogrammers.com/library/mdi/icon/{ICON_NAME)
  ```

We should probably also close https://github.com/Pictogrammers/Browser-Icon-Picker/issues/8 as `wontfix`.

**Comment by chteuchteu** [comment]
+1, thanks for the issue!

**Comment by chteuchteu** [comment]
Done, thanks!
