### ISSUE TITLE
Update the header based on the library you're viewing?

### ISSUE THREAD

**Issue by mririgoyen** [Pictogrammers/Browser-Icon-Picker#99]
Currently the header says "MaterialDesignIcons." First, could we update it to use spaces? (e.g. "Material Design Icons") It should continue to point to <https://pictogrammers.com/library/mdi/>

When you switch the the "Light" library, can that header then say "Material Design Icons Light" and link to <https://pictogrammers.com/library/mdil/>? The icon should be `mdil-vector-combine`.

**Comment by chteuchteu** [comment]
+1, thanks for the subscription!

**Comment by chteuchteu** [comment]
What about using the light library color as header background?

![image](https://user-images.githubusercontent.com/1551971/213791618-1ef23905-0b13-4081-abea-174e20a688b4.png)
